[package]
name = "twtxt_api"
version = "0.1.0"
authors = ["Gil Gon√ßalves <lursty@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-cors = "0.2.0"
actix-rt = "1"
serde = "1.0.0"
